# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'DinoRunner-Demo' do
  use_frameworks!
  
  pod 'DinoRunner'

end
